services:
  mysql_lab: # le service de serveur de bases de données
    container_name: mysql_lab
    image: mysql:8.3
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 40s 
    environment:
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    ports:
      - "3306:3306"
    env_file:
      - .mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ../seed/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ../seed/02_users_accounts.sql:/docker-entrypoint-initdb.d/02_users_accounts.sql
      - ../seed/03_views.sql:/docker-entrypoint-initdb.d/03_views.sql
      - ../seed/04_procedures.sql:/docker-entrypoint-initdb.d/04_procedures.sql
      - ../seed/05_events.sql:/docker-entrypoint-initdb.d/05_events.sql
    

  gui_lab:
    container_name: gui_lab
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .gui.env
    depends_on:
      mysql_lab:
        condition: service_healthy

volumes:
  mysql_data: 